name: flutter_kim
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mvvm_riverpod: ^1.2.0
  # camera: ^0.10.5+5
  # flutter_riverpod: ^2.4.4
  # flutter_storage_path: ^1.0.4
  # gal: ^2.1.2
  # image: ^4.1.3
  # image_picker: ^1.0.4
  # media_info: ^0.7.0
  # path: ^1.8.3
  # path_provider: ^2.1.1
  # permission_handler: ^11.0.1
  # riverpod_annotation: ^2.2.1
  # tflite_flutter: ^0.10.3
  # vector_math: ^2.1.4
  # video_thumbnail: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  # build_runner: ^2.4.6
  # custom_lint: ^0.5.5
  # riverpod_generator: ^2.3.5
  # riverpod_lint: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/lhc/Body_Posture/
    - assets/lhc/Unfavourable_Working_Conditions/
    - assets/model/
    - lib/abp/
    - lib/bm/
    - lib/mho/

flutter_launcher_icons:
  android: "kim_icon"
  image_path: "assets/icon/kim_icon.jpg"
  min_sdk_android: 26